simplify full-workflow call for now; 1 active learner only; not storing to db

diff --git a/start b/start
--- a/start
+++ b/start
@@ -40,6 +40,21 @@ docker run --rm \
 graphql-dev upgrade head
 echo -ne 'migration done\n'
 
+
+MODEL_DIR=${PWD%/*}/dev-setup/model-data/
+if [ ! -d "$MODEL_DIR" ] 
+then
+    MODEL_DIR=${PWD%/*/*}/dev-setup/model-data/
+    if [ ! -d "$MODEL_DIR" ] 
+    then
+        # to include volume for local development, use the dev-setup model data folder:  
+        # alternative use manual logic with
+        # -v /path/to/dev-setup/model-data:/models \
+        echo "Can't find model data directory: $MODEL_DIR -> stopping" 
+        exit 1
+    fi
+fi
+
 echo -ne 'starting...'
 docker run -d --rm \
 --name refinery-gateway \
@@ -66,6 +81,7 @@ docker run -d --rm \
 -e KRATOS_ADMIN_URL=http://kratos:4434 \
 --mount type=bind,source="$(pwd)"/,target=/app \
 -v /var/run/docker.sock:/var/run/docker.sock \
+-v "$MODEL_DIR":/models \
 --network dev-setup_default \
 graphql-dev > /dev/null 2>&1
 echo -ne '\t\t\t [done]\n'
